security:
  password_hashers:
    Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

  providers:
    app_user_provider:
      entity:
        class: App\Entity\User
        property: email

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    # Firewall dédié au login
    login:
      pattern: ^/api/login
      stateless: true
      provider: app_user_provider
      json_login:
        check_path: /api/login
        username_path: email
        password_path: password
        success_handler: lexik_jwt_authentication.handler.authentication_success
        failure_handler: lexik_jwt_authentication.handler.authentication_failure

    # Firewall pour toutes les autres routes protégées
    main:
      pattern: ^/api
      stateless: true
      provider: app_user_provider
      jwt: ~

  access_control:
    - { path: ^/api/login$, roles: PUBLIC_ACCESS }
    - { path: ^/api/events$, roles: PUBLIC_ACCESS, methods: [GET] }
    - { path: ^/api/events/\d+$, roles: PUBLIC_ACCESS, methods: [GET] }
    - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }
