version: '3.8'

services:
  database:
    image: mysql:8.0
    container_name: symfony-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: symfony-phpmyadmin
    restart: always
    environment:
      PMA_HOST: database
      PMA_USER: symfony
      PMA_PASSWORD: symfony
    ports:
      - "8081:80"

volumes:
  db_data:
